package com.icss.model;
// Generated 2018-1-30 10:59:26 by Hibernate Tools 4.3.5.Final

/**
 * City generated by hbm2java
 */
public class City implements java.io.Serializable {

	private String uid;
	private String citycode;
	private String cityname;
	private String countryname;
	private String id;
	private String lat;
	private String lng;
	private String province;

	public City() {
	}

	public City(String uid) {
		this.uid = uid;
	}

	public City(String uid, String citycode, String cityname, String countryname, String id, String lat, String lng,
			String province) {
		this.uid = uid;
		this.citycode = citycode;
		this.cityname = cityname;
		this.countryname = countryname;
		this.id = id;
		this.lat = lat;
		this.lng = lng;
		this.province = province;
	}

	public String getUid() {
		return this.uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	public String getCitycode() {
		return this.citycode;
	}

	public void setCitycode(String citycode) {
		this.citycode = citycode;
	}

	public String getCityname() {
		return this.cityname;
	}

	public void setCityname(String cityname) {
		this.cityname = cityname;
	}

	public String getCountryname() {
		return this.countryname;
	}

	public void setCountryname(String countryname) {
		this.countryname = countryname;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getLat() {
		return this.lat;
	}

	public void setLat(String lat) {
		this.lat = lat;
	}

	public String getLng() {
		return this.lng;
	}

	public void setLng(String lng) {
		this.lng = lng;
	}

	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

}
